### ISSUE TITLE
Demo fails on callback

### ISSUE THREAD

**Issue by Rotabor** [hexagon-oss/Remoting-Replacement#56]
CallbackImpl should be moved to SampleServerClasses to resolve this issue.

**Comment by pgrawehr** [comment]
I'm  not sure I understand what you mean. Are you saying that running the sample app causes an error?

**Comment by Rotabor** [comment]
Yes. It's due to CallbackImpl is in Client and not accessible for Server while it's called in it. It can work if all apps are in the single folder, but it doesn't work if Client and Server are run each from own dedicated folder.

**Comment by pgrawehr** [comment]
This is expected. Both client and server need to have access to the same set of dll files. So if you have them run from two different directories (or even on two different computers), you still need to make sure that both sides share the full set of libraries. Both sides need access to the full type info for all used classes. If you use the build script to create the solution, you can run both client and server from their respective bin folders or from a common folder. 

The next version will - for some use cases - remove that requirement, but for the cost of tighter requirements on the structure of marshallable classes and their interfaces.

**Comment by Rotabor** [comment]
Ok. Just check in which dll CallbackImpl resides.

**Comment by pgrawehr** [comment]
It's in the client, yes. But if the server has access to that library, all should be fine. At least, I'm not able to reproduce the issue. Can you give exact reproduction steps, please?

**Comment by Rotabor** [comment]
I downloaded the project and compiled it. Then run Server from its folder,
then run Client from its folder. Client performs few steps and fails at
"cls.RegisterCallback(cbi);" reporting something like "Server shutdown".
When I debugged the server, it failed to load "RemotingClient.dll" where
CallbackImpl resides. Evidently, "RemotingClient.dll" can be far far away
in another galaxy. The only shared library in the demo is
SampleServerClasses where CallbackImpl can be placed (or in another shared
library, but not in the client code).

Br,

Alexei.

чт, 14 мар. 2024 г. в 15:22, Patrick Grawehr ***@***.***>:

**Comment by pgrawehr** [comment]
As I said, the server needs access to the client dll's (so they need to have been copied there somehow). If you run the `build.cmd` script in the root folder everything is prepared for you. It's also possible to have the client copy its own binaries to the server by the use of the `IRemoteServerService` interface.

**Comment by Rotabor** [comment]
One good thing is that it is not done as you claim. I moved CallbackImpl from Client's library to a shared library, and the Server works fine without access to Client's library. Otherwise, it would be a complete discredit to the very idea of remote execution. You can close this issue. After all, this is a non-priority issue with demo code only.
